# Generated by Django 3.2.16 on 2022-11-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'house', 'verbose_name_plural': 'houses'},
        ),
    ]
