# Generated by Django 3.2.16 on 2022-11-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'verbose_name': 'house', 'verbose_name_plural': 'houses'},
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='houses\\images', verbose_name='image'),
        ),
    ]
